### ISSUE TITLE
It should be there?

### ISSUE THREAD

**Issue by MSadeghzadehG** [AUT-CEIT/UDPNoise#1]
Hi, I'm watching the aut-ce repositories to check the conformity of them with contribution-guide. is it necessary to be in this organization?

**Comment by 1995parham** [comment]
I agree with your suggestion. I have a plan to move this into my projects. In the beginning, it was used in the CN course to validate students' implementation of a reliable UDP protocol.

**Comment by 1995parham** [comment]
I have moved it from @aut-ce into @elahe-dastan account. She accepted its maintenance.
